// Automatically generated by odin - do not edit
#include <R.h>
#include <Rmath.h>
#include <Rinternals.h>
#include <stdbool.h>
#include <R_ext/Rdynload.h>
#ifndef CINTERPOLTE_CINTERPOLATE_H_
#define CINTERPOLTE_CINTERPOLATE_H_

// Allow use from C++
#ifdef __cplusplus
extern "C" {
#endif

// There are only three functions in the interface; allocation,
// evaluation and freeing.

// Allocate an interpolation object.
//
//   type: The mode of interpolation. Must be one of "constant",
//       "linear" or "spline" (an R error is thrown if a different
//       value is given).
//
//   n: The number of `x` points to interpolate over
//
//   ny: the number of `y` points per `x` point.  This is 1 in the
//       case of zimple interpolation as used by Rs `interpolate()`
//
//   x: an array of `x` values of length `n`
//
//   y: an array of `ny` sets of `y` values.  This is in R's matrix
//       order (i.e., the first `n` values are the first series to
//       interpolate over).
//
//   fail_on_extrapolate: if true, when an extrapolation occurs throw
//       an error; if false return NA_REAL
//
//   auto_free: automatically clean up the interpolation object on
//       return to R. This uses `R_alloc` for allocations rather than
//       `Calloc` so freeing will always happen (even on error
//       elsewhere in the code). However, this prevents returning back
//       a pointer to R that will last longer than the call into C
//       code.
//
// The return value is an opaque pointer that can be passed through to
// `cinterpolate_eval` and `cinterpolate_free`
void *cinterpolate_alloc(const char *type, size_t n, size_t ny,
                         double *x, double *y, bool fail_on_extrapolate,
                         bool auto_free);

// Evaluate the interpolated function at a new `x` point.
//
//   x: A new, single, `x` point to interpolate `y` values to
//
//   obj: The interpolation object, as returned by `cinterpolate_alloc`
//
//   y: An array of length `ny` to store the interpolated values
//
// The return value is 0 if the interpolation is successful (with x
// lying within the range of values that the interpolation function
// supports), -1 otherwise
int cinterpolate_eval(double x, void *obj, double *y);

// Clean up all allocated memory
//
//   obj: The interpolation object, as returned by `cinterpolate_alloc`
void cinterpolate_free(void *obj);

#ifdef __cplusplus
}
#endif

#endif
typedef struct SEIR_internal {
  double *beta_set;
  double *delta_E1;
  double *delta_E2;
  double *delta_I;
  double *delta_R;
  int dim_beta_set;
  int dim_delta_E1;
  int dim_delta_E2;
  int dim_delta_I;
  int dim_delta_R;
  int dim_E0;
  int dim_E02;
  int dim_E1;
  int dim_E2;
  int dim_I;
  int dim_I0;
  int dim_lambda;
  int dim_m;
  int dim_m_1;
  int dim_m_2;
  int dim_mix_mat_set;
  int dim_mix_mat_set_1;
  int dim_mix_mat_set_12;
  int dim_mix_mat_set_2;
  int dim_mix_mat_set_3;
  int dim_n_EE;
  int dim_n_EI;
  int dim_n_IR;
  int dim_n_SE;
  int dim_p_SE;
  int dim_R;
  int dim_R0;
  int dim_S;
  int dim_s_ij;
  int dim_s_ij_1;
  int dim_s_ij_2;
  int dim_S0;
  int dim_temp;
  int dim_tt_beta;
  int dim_tt_matrix;
  double dt;
  double *E0;
  double *E02;
  double gamma_E;
  double gamma_I;
  double *I0;
  double *initial_E1;
  double *initial_E2;
  double *initial_I;
  double *initial_R;
  double *initial_S;
  void *interpolate_beta;
  void *interpolate_m;
  double *lambda;
  double *m;
  double *mix_mat_set;
  int N_age;
  double *n_EE;
  double *n_EI;
  double *n_IR;
  double *n_SE;
  int offset_variable_E2;
  int offset_variable_I;
  int offset_variable_R;
  double p_EE;
  double p_EI;
  double p_IR;
  double *p_SE;
  double *R0;
  double *s_ij;
  double *S0;
  double *temp;
  double *tt_beta;
  double *tt_matrix;
} SEIR_internal;
SEIR_internal* SEIR_get_internal(SEXP internal_p, int closed_error);
static void SEIR_finalise(SEXP internal_p);
SEXP SEIR_create(SEXP user);
void SEIR_initmod_desolve(void(* odeparms) (int *, double *));
SEXP SEIR_contents(SEXP internal_p);
SEXP SEIR_set_user(SEXP internal_p, SEXP user);
SEXP SEIR_metadata(SEXP internal_p);
SEXP SEIR_initial_conditions(SEXP internal_p, SEXP step_ptr);
void SEIR_rhs(SEIR_internal* internal, size_t step, double * state, double * state_next, double * output);
void SEIR_rhs_dde(size_t n_eq, size_t step, double * state, double * state_next, size_t n_out, double * output, void * internal);
SEXP SEIR_rhs_r(SEXP internal_p, SEXP step, SEXP state);
double user_get_scalar_double(SEXP user, const char *name,
                              double default_value, double min, double max);
int user_get_scalar_int(SEXP user, const char *name,
                        int default_value, double min, double max);
void user_check_values_double(double * value, size_t len,
                                  double min, double max, const char *name);
void user_check_values_int(int * value, size_t len,
                               double min, double max, const char *name);
void user_check_values(SEXP value, double min, double max,
                           const char *name);
SEXP user_list_element(SEXP list, const char *name);
void odin_set_dim(SEXP target, int rank, ...);
void* user_get_array_dim(SEXP user, bool is_integer, void * previous,
                         const char *name, int rank,
                         double min, double max, int *dest_dim);
void* user_get_array(SEXP user, bool is_integer, void * previous,
                     const char *name, double min, double max,
                     int rank, ...);
SEXP user_get_array_check(SEXP el, bool is_integer, const char *name,
                          double min, double max);
SEXP user_get_array_check_rank(SEXP user, const char *name, int rank,
                               bool required);
void interpolate_check_y(size_t nx, size_t ny, size_t i, const char *name_arg, const char *name_target);
double odin_sum1(double *x, size_t from, size_t to);
double odin_sum2(double* x, int from_i, int to_i, int from_j, int to_j, int dim_x_1);
double odin_sum3(double* x, int from_i, int to_i, int from_j, int to_j, int from_k, int to_k, int dim_x_1, int dim_x_12);
SEIR_internal* SEIR_get_internal(SEXP internal_p, int closed_error) {
  SEIR_internal *internal = NULL;
  if (TYPEOF(internal_p) != EXTPTRSXP) {
    Rf_error("Expected an external pointer");
  }
  internal = (SEIR_internal*) R_ExternalPtrAddr(internal_p);
  if (!internal && closed_error) {
    Rf_error("Pointer has been invalidated");
  }
  return internal;
}
void SEIR_finalise(SEXP internal_p) {
  SEIR_internal *internal = SEIR_get_internal(internal_p, 0);
  if (internal_p) {
    cinterpolate_free(internal->interpolate_beta);
    cinterpolate_free(internal->interpolate_m);
    internal->interpolate_beta = NULL;
    internal->interpolate_m = NULL;
    Free(internal->beta_set);
    Free(internal->delta_E1);
    Free(internal->delta_E2);
    Free(internal->delta_I);
    Free(internal->delta_R);
    Free(internal->E0);
    Free(internal->E02);
    Free(internal->I0);
    Free(internal->initial_E1);
    Free(internal->initial_E2);
    Free(internal->initial_I);
    Free(internal->initial_R);
    Free(internal->initial_S);
    Free(internal->lambda);
    Free(internal->m);
    Free(internal->mix_mat_set);
    Free(internal->n_EE);
    Free(internal->n_EI);
    Free(internal->n_IR);
    Free(internal->n_SE);
    Free(internal->p_SE);
    Free(internal->R0);
    Free(internal->s_ij);
    Free(internal->S0);
    Free(internal->temp);
    Free(internal->tt_beta);
    Free(internal->tt_matrix);
    Free(internal);
    R_ClearExternalPtr(internal_p);
  }
}
SEXP SEIR_create(SEXP user) {
  SEIR_internal *internal = (SEIR_internal*) Calloc(1, SEIR_internal);
  internal->beta_set = NULL;
  internal->delta_E1 = NULL;
  internal->delta_E2 = NULL;
  internal->delta_I = NULL;
  internal->delta_R = NULL;
  internal->E0 = NULL;
  internal->E02 = NULL;
  internal->I0 = NULL;
  internal->initial_E1 = NULL;
  internal->initial_E2 = NULL;
  internal->initial_I = NULL;
  internal->initial_R = NULL;
  internal->initial_S = NULL;
  internal->interpolate_m = NULL;
  internal->lambda = NULL;
  internal->m = NULL;
  internal->mix_mat_set = NULL;
  internal->n_EE = NULL;
  internal->n_EI = NULL;
  internal->n_IR = NULL;
  internal->n_SE = NULL;
  internal->p_SE = NULL;
  internal->R0 = NULL;
  internal->s_ij = NULL;
  internal->S0 = NULL;
  internal->temp = NULL;
  internal->tt_beta = NULL;
  internal->tt_matrix = NULL;
  internal->beta_set = NULL;
  internal->dt = NA_REAL;
  internal->E0 = NULL;
  internal->E02 = NULL;
  internal->gamma_E = NA_REAL;
  internal->gamma_I = NA_REAL;
  internal->I0 = NULL;
  internal->mix_mat_set = NULL;
  internal->N_age = NA_INTEGER;
  internal->R0 = NULL;
  internal->S0 = NULL;
  internal->tt_beta = NULL;
  internal->tt_matrix = NULL;
  SEXP ptr = PROTECT(R_MakeExternalPtr(internal, R_NilValue, R_NilValue));
  R_RegisterCFinalizer(ptr, SEIR_finalise);
  UNPROTECT(1);
  return ptr;
}
static SEIR_internal *SEIR_internal_ds;
void SEIR_initmod_desolve(void(* odeparms) (int *, double *)) {
  static DL_FUNC get_desolve_gparms = NULL;
  if (get_desolve_gparms == NULL) {
    get_desolve_gparms =
      R_GetCCallable("deSolve", "get_deSolve_gparms");
  }
  SEIR_internal_ds = SEIR_get_internal(get_desolve_gparms(), 1);
}
SEXP SEIR_contents(SEXP internal_p) {
  SEIR_internal *internal = SEIR_get_internal(internal_p, 1);
  SEXP contents = PROTECT(allocVector(VECSXP, 74));
  SEXP beta_set = PROTECT(allocVector(REALSXP, internal->dim_beta_set));
  memcpy(REAL(beta_set), internal->beta_set, internal->dim_beta_set * sizeof(double));
  SET_VECTOR_ELT(contents, 0, beta_set);
  SEXP delta_E1 = PROTECT(allocVector(REALSXP, internal->dim_delta_E1));
  memcpy(REAL(delta_E1), internal->delta_E1, internal->dim_delta_E1 * sizeof(double));
  SET_VECTOR_ELT(contents, 1, delta_E1);
  SEXP delta_E2 = PROTECT(allocVector(REALSXP, internal->dim_delta_E2));
  memcpy(REAL(delta_E2), internal->delta_E2, internal->dim_delta_E2 * sizeof(double));
  SET_VECTOR_ELT(contents, 2, delta_E2);
  SEXP delta_I = PROTECT(allocVector(REALSXP, internal->dim_delta_I));
  memcpy(REAL(delta_I), internal->delta_I, internal->dim_delta_I * sizeof(double));
  SET_VECTOR_ELT(contents, 3, delta_I);
  SEXP delta_R = PROTECT(allocVector(REALSXP, internal->dim_delta_R));
  memcpy(REAL(delta_R), internal->delta_R, internal->dim_delta_R * sizeof(double));
  SET_VECTOR_ELT(contents, 4, delta_R);
  SET_VECTOR_ELT(contents, 5, ScalarInteger(internal->dim_beta_set));
  SET_VECTOR_ELT(contents, 6, ScalarInteger(internal->dim_delta_E1));
  SET_VECTOR_ELT(contents, 7, ScalarInteger(internal->dim_delta_E2));
  SET_VECTOR_ELT(contents, 8, ScalarInteger(internal->dim_delta_I));
  SET_VECTOR_ELT(contents, 9, ScalarInteger(internal->dim_delta_R));
  SET_VECTOR_ELT(contents, 10, ScalarInteger(internal->dim_E0));
  SET_VECTOR_ELT(contents, 11, ScalarInteger(internal->dim_E02));
  SET_VECTOR_ELT(contents, 12, ScalarInteger(internal->dim_E1));
  SET_VECTOR_ELT(contents, 13, ScalarInteger(internal->dim_E2));
  SET_VECTOR_ELT(contents, 14, ScalarInteger(internal->dim_I));
  SET_VECTOR_ELT(contents, 15, ScalarInteger(internal->dim_I0));
  SET_VECTOR_ELT(contents, 16, ScalarInteger(internal->dim_lambda));
  SET_VECTOR_ELT(contents, 17, ScalarInteger(internal->dim_m));
  SET_VECTOR_ELT(contents, 18, ScalarInteger(internal->dim_m_1));
  SET_VECTOR_ELT(contents, 19, ScalarInteger(internal->dim_m_2));
  SET_VECTOR_ELT(contents, 20, ScalarInteger(internal->dim_mix_mat_set));
  SET_VECTOR_ELT(contents, 21, ScalarInteger(internal->dim_mix_mat_set_1));
  SET_VECTOR_ELT(contents, 22, ScalarInteger(internal->dim_mix_mat_set_12));
  SET_VECTOR_ELT(contents, 23, ScalarInteger(internal->dim_mix_mat_set_2));
  SET_VECTOR_ELT(contents, 24, ScalarInteger(internal->dim_mix_mat_set_3));
  SET_VECTOR_ELT(contents, 25, ScalarInteger(internal->dim_n_EE));
  SET_VECTOR_ELT(contents, 26, ScalarInteger(internal->dim_n_EI));
  SET_VECTOR_ELT(contents, 27, ScalarInteger(internal->dim_n_IR));
  SET_VECTOR_ELT(contents, 28, ScalarInteger(internal->dim_n_SE));
  SET_VECTOR_ELT(contents, 29, ScalarInteger(internal->dim_p_SE));
  SET_VECTOR_ELT(contents, 30, ScalarInteger(internal->dim_R));
  SET_VECTOR_ELT(contents, 31, ScalarInteger(internal->dim_R0));
  SET_VECTOR_ELT(contents, 32, ScalarInteger(internal->dim_S));
  SET_VECTOR_ELT(contents, 33, ScalarInteger(internal->dim_s_ij));
  SET_VECTOR_ELT(contents, 34, ScalarInteger(internal->dim_s_ij_1));
  SET_VECTOR_ELT(contents, 35, ScalarInteger(internal->dim_s_ij_2));
  SET_VECTOR_ELT(contents, 36, ScalarInteger(internal->dim_S0));
  SET_VECTOR_ELT(contents, 37, ScalarInteger(internal->dim_temp));
  SET_VECTOR_ELT(contents, 38, ScalarInteger(internal->dim_tt_beta));
  SET_VECTOR_ELT(contents, 39, ScalarInteger(internal->dim_tt_matrix));
  SET_VECTOR_ELT(contents, 40, ScalarReal(internal->dt));
  SEXP E0 = PROTECT(allocVector(REALSXP, internal->dim_E0));
  memcpy(REAL(E0), internal->E0, internal->dim_E0 * sizeof(double));
  SET_VECTOR_ELT(contents, 41, E0);
  SEXP E02 = PROTECT(allocVector(REALSXP, internal->dim_E02));
  memcpy(REAL(E02), internal->E02, internal->dim_E02 * sizeof(double));
  SET_VECTOR_ELT(contents, 42, E02);
  SET_VECTOR_ELT(contents, 43, ScalarReal(internal->gamma_E));
  SET_VECTOR_ELT(contents, 44, ScalarReal(internal->gamma_I));
  SEXP I0 = PROTECT(allocVector(REALSXP, internal->dim_I0));
  memcpy(REAL(I0), internal->I0, internal->dim_I0 * sizeof(double));
  SET_VECTOR_ELT(contents, 45, I0);
  SEXP initial_E1 = PROTECT(allocVector(REALSXP, internal->dim_E1));
  memcpy(REAL(initial_E1), internal->initial_E1, internal->dim_E1 * sizeof(double));
  SET_VECTOR_ELT(contents, 46, initial_E1);
  SEXP initial_E2 = PROTECT(allocVector(REALSXP, internal->dim_E2));
  memcpy(REAL(initial_E2), internal->initial_E2, internal->dim_E2 * sizeof(double));
  SET_VECTOR_ELT(contents, 47, initial_E2);
  SEXP initial_I = PROTECT(allocVector(REALSXP, internal->dim_I));
  memcpy(REAL(initial_I), internal->initial_I, internal->dim_I * sizeof(double));
  SET_VECTOR_ELT(contents, 48, initial_I);
  SEXP initial_R = PROTECT(allocVector(REALSXP, internal->dim_R));
  memcpy(REAL(initial_R), internal->initial_R, internal->dim_R * sizeof(double));
  SET_VECTOR_ELT(contents, 49, initial_R);
  SEXP initial_S = PROTECT(allocVector(REALSXP, internal->dim_S));
  memcpy(REAL(initial_S), internal->initial_S, internal->dim_S * sizeof(double));
  SET_VECTOR_ELT(contents, 50, initial_S);
  SEXP lambda = PROTECT(allocVector(REALSXP, internal->dim_lambda));
  memcpy(REAL(lambda), internal->lambda, internal->dim_lambda * sizeof(double));
  SET_VECTOR_ELT(contents, 53, lambda);
  SEXP m = PROTECT(allocVector(REALSXP, internal->dim_m));
  memcpy(REAL(m), internal->m, internal->dim_m * sizeof(double));
  odin_set_dim(m, 2, internal->dim_m_1, internal->dim_m_2);
  SET_VECTOR_ELT(contents, 54, m);
  SEXP mix_mat_set = PROTECT(allocVector(REALSXP, internal->dim_mix_mat_set));
  memcpy(REAL(mix_mat_set), internal->mix_mat_set, internal->dim_mix_mat_set * sizeof(double));
  odin_set_dim(mix_mat_set, 3, internal->dim_mix_mat_set_1, internal->dim_mix_mat_set_2, internal->dim_mix_mat_set_3);
  SET_VECTOR_ELT(contents, 55, mix_mat_set);
  SET_VECTOR_ELT(contents, 56, ScalarInteger(internal->N_age));
  SEXP n_EE = PROTECT(allocVector(REALSXP, internal->dim_n_EE));
  memcpy(REAL(n_EE), internal->n_EE, internal->dim_n_EE * sizeof(double));
  SET_VECTOR_ELT(contents, 57, n_EE);
  SEXP n_EI = PROTECT(allocVector(REALSXP, internal->dim_n_EI));
  memcpy(REAL(n_EI), internal->n_EI, internal->dim_n_EI * sizeof(double));
  SET_VECTOR_ELT(contents, 58, n_EI);
  SEXP n_IR = PROTECT(allocVector(REALSXP, internal->dim_n_IR));
  memcpy(REAL(n_IR), internal->n_IR, internal->dim_n_IR * sizeof(double));
  SET_VECTOR_ELT(contents, 59, n_IR);
  SEXP n_SE = PROTECT(allocVector(REALSXP, internal->dim_n_SE));
  memcpy(REAL(n_SE), internal->n_SE, internal->dim_n_SE * sizeof(double));
  SET_VECTOR_ELT(contents, 60, n_SE);
  SET_VECTOR_ELT(contents, 61, ScalarInteger(internal->offset_variable_E2));
  SET_VECTOR_ELT(contents, 62, ScalarInteger(internal->offset_variable_I));
  SET_VECTOR_ELT(contents, 63, ScalarInteger(internal->offset_variable_R));
  SET_VECTOR_ELT(contents, 64, ScalarReal(internal->p_EE));
  SET_VECTOR_ELT(contents, 65, ScalarReal(internal->p_EI));
  SET_VECTOR_ELT(contents, 66, ScalarReal(internal->p_IR));
  SEXP p_SE = PROTECT(allocVector(REALSXP, internal->dim_p_SE));
  memcpy(REAL(p_SE), internal->p_SE, internal->dim_p_SE * sizeof(double));
  SET_VECTOR_ELT(contents, 67, p_SE);
  SEXP R0 = PROTECT(allocVector(REALSXP, internal->dim_R0));
  memcpy(REAL(R0), internal->R0, internal->dim_R0 * sizeof(double));
  SET_VECTOR_ELT(contents, 68, R0);
  SEXP s_ij = PROTECT(allocVector(REALSXP, internal->dim_s_ij));
  memcpy(REAL(s_ij), internal->s_ij, internal->dim_s_ij * sizeof(double));
  odin_set_dim(s_ij, 2, internal->dim_s_ij_1, internal->dim_s_ij_2);
  SET_VECTOR_ELT(contents, 69, s_ij);
  SEXP S0 = PROTECT(allocVector(REALSXP, internal->dim_S0));
  memcpy(REAL(S0), internal->S0, internal->dim_S0 * sizeof(double));
  SET_VECTOR_ELT(contents, 70, S0);
  SEXP temp = PROTECT(allocVector(REALSXP, internal->dim_temp));
  memcpy(REAL(temp), internal->temp, internal->dim_temp * sizeof(double));
  SET_VECTOR_ELT(contents, 71, temp);
  SEXP tt_beta = PROTECT(allocVector(REALSXP, internal->dim_tt_beta));
  memcpy(REAL(tt_beta), internal->tt_beta, internal->dim_tt_beta * sizeof(double));
  SET_VECTOR_ELT(contents, 72, tt_beta);
  SEXP tt_matrix = PROTECT(allocVector(REALSXP, internal->dim_tt_matrix));
  memcpy(REAL(tt_matrix), internal->tt_matrix, internal->dim_tt_matrix * sizeof(double));
  SET_VECTOR_ELT(contents, 73, tt_matrix);
  SEXP nms = PROTECT(allocVector(STRSXP, 74));
  SET_STRING_ELT(nms, 0, mkChar("beta_set"));
  SET_STRING_ELT(nms, 1, mkChar("delta_E1"));
  SET_STRING_ELT(nms, 2, mkChar("delta_E2"));
  SET_STRING_ELT(nms, 3, mkChar("delta_I"));
  SET_STRING_ELT(nms, 4, mkChar("delta_R"));
  SET_STRING_ELT(nms, 5, mkChar("dim_beta_set"));
  SET_STRING_ELT(nms, 6, mkChar("dim_delta_E1"));
  SET_STRING_ELT(nms, 7, mkChar("dim_delta_E2"));
  SET_STRING_ELT(nms, 8, mkChar("dim_delta_I"));
  SET_STRING_ELT(nms, 9, mkChar("dim_delta_R"));
  SET_STRING_ELT(nms, 10, mkChar("dim_E0"));
  SET_STRING_ELT(nms, 11, mkChar("dim_E02"));
  SET_STRING_ELT(nms, 12, mkChar("dim_E1"));
  SET_STRING_ELT(nms, 13, mkChar("dim_E2"));
  SET_STRING_ELT(nms, 14, mkChar("dim_I"));
  SET_STRING_ELT(nms, 15, mkChar("dim_I0"));
  SET_STRING_ELT(nms, 16, mkChar("dim_lambda"));
  SET_STRING_ELT(nms, 17, mkChar("dim_m"));
  SET_STRING_ELT(nms, 18, mkChar("dim_m_1"));
  SET_STRING_ELT(nms, 19, mkChar("dim_m_2"));
  SET_STRING_ELT(nms, 20, mkChar("dim_mix_mat_set"));
  SET_STRING_ELT(nms, 21, mkChar("dim_mix_mat_set_1"));
  SET_STRING_ELT(nms, 22, mkChar("dim_mix_mat_set_12"));
  SET_STRING_ELT(nms, 23, mkChar("dim_mix_mat_set_2"));
  SET_STRING_ELT(nms, 24, mkChar("dim_mix_mat_set_3"));
  SET_STRING_ELT(nms, 25, mkChar("dim_n_EE"));
  SET_STRING_ELT(nms, 26, mkChar("dim_n_EI"));
  SET_STRING_ELT(nms, 27, mkChar("dim_n_IR"));
  SET_STRING_ELT(nms, 28, mkChar("dim_n_SE"));
  SET_STRING_ELT(nms, 29, mkChar("dim_p_SE"));
  SET_STRING_ELT(nms, 30, mkChar("dim_R"));
  SET_STRING_ELT(nms, 31, mkChar("dim_R0"));
  SET_STRING_ELT(nms, 32, mkChar("dim_S"));
  SET_STRING_ELT(nms, 33, mkChar("dim_s_ij"));
  SET_STRING_ELT(nms, 34, mkChar("dim_s_ij_1"));
  SET_STRING_ELT(nms, 35, mkChar("dim_s_ij_2"));
  SET_STRING_ELT(nms, 36, mkChar("dim_S0"));
  SET_STRING_ELT(nms, 37, mkChar("dim_temp"));
  SET_STRING_ELT(nms, 38, mkChar("dim_tt_beta"));
  SET_STRING_ELT(nms, 39, mkChar("dim_tt_matrix"));
  SET_STRING_ELT(nms, 40, mkChar("dt"));
  SET_STRING_ELT(nms, 41, mkChar("E0"));
  SET_STRING_ELT(nms, 42, mkChar("E02"));
  SET_STRING_ELT(nms, 43, mkChar("gamma_E"));
  SET_STRING_ELT(nms, 44, mkChar("gamma_I"));
  SET_STRING_ELT(nms, 45, mkChar("I0"));
  SET_STRING_ELT(nms, 46, mkChar("initial_E1"));
  SET_STRING_ELT(nms, 47, mkChar("initial_E2"));
  SET_STRING_ELT(nms, 48, mkChar("initial_I"));
  SET_STRING_ELT(nms, 49, mkChar("initial_R"));
  SET_STRING_ELT(nms, 50, mkChar("initial_S"));
  SET_STRING_ELT(nms, 51, mkChar("interpolate_beta"));
  SET_STRING_ELT(nms, 52, mkChar("interpolate_m"));
  SET_STRING_ELT(nms, 53, mkChar("lambda"));
  SET_STRING_ELT(nms, 54, mkChar("m"));
  SET_STRING_ELT(nms, 55, mkChar("mix_mat_set"));
  SET_STRING_ELT(nms, 56, mkChar("N_age"));
  SET_STRING_ELT(nms, 57, mkChar("n_EE"));
  SET_STRING_ELT(nms, 58, mkChar("n_EI"));
  SET_STRING_ELT(nms, 59, mkChar("n_IR"));
  SET_STRING_ELT(nms, 60, mkChar("n_SE"));
  SET_STRING_ELT(nms, 61, mkChar("offset_variable_E2"));
  SET_STRING_ELT(nms, 62, mkChar("offset_variable_I"));
  SET_STRING_ELT(nms, 63, mkChar("offset_variable_R"));
  SET_STRING_ELT(nms, 64, mkChar("p_EE"));
  SET_STRING_ELT(nms, 65, mkChar("p_EI"));
  SET_STRING_ELT(nms, 66, mkChar("p_IR"));
  SET_STRING_ELT(nms, 67, mkChar("p_SE"));
  SET_STRING_ELT(nms, 68, mkChar("R0"));
  SET_STRING_ELT(nms, 69, mkChar("s_ij"));
  SET_STRING_ELT(nms, 70, mkChar("S0"));
  SET_STRING_ELT(nms, 71, mkChar("temp"));
  SET_STRING_ELT(nms, 72, mkChar("tt_beta"));
  SET_STRING_ELT(nms, 73, mkChar("tt_matrix"));
  setAttrib(contents, R_NamesSymbol, nms);
  UNPROTECT(29);
  return contents;
}
SEXP SEIR_set_user(SEXP internal_p, SEXP user) {
  SEIR_internal *internal = SEIR_get_internal(internal_p, 1);
  internal->dt = user_get_scalar_double(user, "dt", internal->dt, NA_REAL, NA_REAL);
  internal->gamma_E = user_get_scalar_double(user, "gamma_E", internal->gamma_E, NA_REAL, NA_REAL);
  internal->gamma_I = user_get_scalar_double(user, "gamma_I", internal->gamma_I, NA_REAL, NA_REAL);
  internal->N_age = user_get_scalar_int(user, "N_age", internal->N_age, NA_REAL, NA_REAL);
  internal->tt_beta = (double*) user_get_array_dim(user, false, internal->tt_beta, "tt_beta", 1, NA_REAL, NA_REAL, &internal->dim_tt_beta);
  internal->tt_matrix = (double*) user_get_array_dim(user, false, internal->tt_matrix, "tt_matrix", 1, NA_REAL, NA_REAL, &internal->dim_tt_matrix);
  internal->dim_delta_E1 = internal->N_age;
  internal->dim_delta_E2 = internal->N_age;
  internal->dim_delta_I = internal->N_age;
  internal->dim_delta_R = internal->N_age;
  internal->dim_E0 = internal->N_age;
  internal->dim_E02 = internal->N_age;
  internal->dim_E1 = internal->N_age;
  internal->dim_E2 = internal->N_age;
  internal->dim_I = internal->N_age;
  internal->dim_I0 = internal->N_age;
  internal->dim_lambda = internal->N_age;
  internal->dim_m_1 = internal->N_age;
  internal->dim_m_2 = internal->N_age;
  internal->dim_n_EE = internal->N_age;
  internal->dim_n_EI = internal->N_age;
  internal->dim_n_IR = internal->N_age;
  internal->dim_n_SE = internal->N_age;
  internal->dim_p_SE = internal->N_age;
  internal->dim_R = internal->N_age;
  internal->dim_R0 = internal->N_age;
  internal->dim_S = internal->N_age;
  internal->dim_s_ij_1 = internal->N_age;
  internal->dim_s_ij_2 = internal->N_age;
  internal->dim_S0 = internal->N_age;
  internal->dim_temp = internal->N_age;
  internal->p_EE = 1 - exp(-(internal->gamma_E) * internal->dt);
  internal->p_EI = 1 - exp(-(internal->gamma_E) * internal->dt);
  internal->p_IR = 1 - exp(-(internal->gamma_I) * internal->dt);
  Free(internal->delta_E1);
  internal->delta_E1 = (double*) Calloc(internal->dim_delta_E1, double);
  Free(internal->delta_E2);
  internal->delta_E2 = (double*) Calloc(internal->dim_delta_E2, double);
  Free(internal->delta_I);
  internal->delta_I = (double*) Calloc(internal->dim_delta_I, double);
  Free(internal->delta_R);
  internal->delta_R = (double*) Calloc(internal->dim_delta_R, double);
  Free(internal->initial_E1);
  internal->initial_E1 = (double*) Calloc(internal->dim_E1, double);
  Free(internal->initial_E2);
  internal->initial_E2 = (double*) Calloc(internal->dim_E2, double);
  Free(internal->initial_I);
  internal->initial_I = (double*) Calloc(internal->dim_I, double);
  Free(internal->initial_R);
  internal->initial_R = (double*) Calloc(internal->dim_R, double);
  Free(internal->initial_S);
  internal->initial_S = (double*) Calloc(internal->dim_S, double);
  Free(internal->lambda);
  internal->lambda = (double*) Calloc(internal->dim_lambda, double);
  Free(internal->n_EE);
  internal->n_EE = (double*) Calloc(internal->dim_n_EE, double);
  Free(internal->n_EI);
  internal->n_EI = (double*) Calloc(internal->dim_n_EI, double);
  Free(internal->n_IR);
  internal->n_IR = (double*) Calloc(internal->dim_n_IR, double);
  Free(internal->n_SE);
  internal->n_SE = (double*) Calloc(internal->dim_n_SE, double);
  Free(internal->p_SE);
  internal->p_SE = (double*) Calloc(internal->dim_p_SE, double);
  Free(internal->temp);
  internal->temp = (double*) Calloc(internal->dim_temp, double);
  internal->dim_beta_set = internal->dim_tt_beta;
  internal->dim_m = internal->dim_m_1 * internal->dim_m_2;
  internal->dim_mix_mat_set_1 = internal->dim_tt_matrix;
  internal->dim_mix_mat_set_2 = internal->N_age;
  internal->dim_mix_mat_set_3 = internal->N_age;
  internal->dim_s_ij = internal->dim_s_ij_1 * internal->dim_s_ij_2;
  internal->E0 = (double*) user_get_array(user, false, internal->E0, "E0", NA_REAL, NA_REAL, 1, internal->dim_E0);
  internal->E02 = (double*) user_get_array(user, false, internal->E02, "E02", NA_REAL, NA_REAL, 1, internal->dim_E02);
  internal->I0 = (double*) user_get_array(user, false, internal->I0, "I0", NA_REAL, NA_REAL, 1, internal->dim_I0);
  internal->offset_variable_E2 = internal->dim_S + internal->dim_E1;
  internal->offset_variable_I = internal->dim_S + internal->dim_E1 + internal->dim_E2;
  internal->offset_variable_R = internal->dim_S + internal->dim_E1 + internal->dim_E2 + internal->dim_I;
  internal->R0 = (double*) user_get_array(user, false, internal->R0, "R0", NA_REAL, NA_REAL, 1, internal->dim_R0);
  internal->S0 = (double*) user_get_array(user, false, internal->S0, "S0", NA_REAL, NA_REAL, 1, internal->dim_S0);
  Free(internal->m);
  internal->m = (double*) Calloc(internal->dim_m, double);
  Free(internal->s_ij);
  internal->s_ij = (double*) Calloc(internal->dim_s_ij, double);
  internal->beta_set = (double*) user_get_array(user, false, internal->beta_set, "beta_set", NA_REAL, NA_REAL, 1, internal->dim_beta_set);
  internal->dim_mix_mat_set = internal->dim_mix_mat_set_1 * internal->dim_mix_mat_set_2 * internal->dim_mix_mat_set_3;
  internal->dim_mix_mat_set_12 = internal->dim_mix_mat_set_1 * internal->dim_mix_mat_set_2;
  for (int i = 1; i <= internal->dim_E1; ++i) {
    internal->initial_E1[i - 1] = internal->E0[i - 1];
  }
  for (int i = 1; i <= internal->dim_E2; ++i) {
    internal->initial_E2[i - 1] = internal->E02[i - 1];
  }
  for (int i = 1; i <= internal->dim_I; ++i) {
    internal->initial_I[i - 1] = internal->I0[i - 1];
  }
  for (int i = 1; i <= internal->dim_R; ++i) {
    internal->initial_R[i - 1] = internal->R0[i - 1];
  }
  for (int i = 1; i <= internal->dim_S; ++i) {
    internal->initial_S[i - 1] = internal->S0[i - 1];
  }
  interpolate_check_y(internal->dim_tt_beta, internal->dim_beta_set, 0, "beta_set", "beta");
  cinterpolate_free(internal->interpolate_beta);
  internal->interpolate_beta = cinterpolate_alloc("constant", internal->dim_tt_beta, 1, internal->tt_beta, internal->beta_set, true, false);
  internal->mix_mat_set = (double*) user_get_array(user, false, internal->mix_mat_set, "mix_mat_set", NA_REAL, NA_REAL, 3, internal->dim_mix_mat_set_1, internal->dim_mix_mat_set_2, internal->dim_mix_mat_set_3);
  interpolate_check_y(internal->dim_tt_matrix, internal->dim_mix_mat_set_1, 1, "mix_mat_set", "m");
  interpolate_check_y(internal->dim_m_1, internal->dim_mix_mat_set_2, 2, "mix_mat_set", "m");
  interpolate_check_y(internal->dim_m_2, internal->dim_mix_mat_set_3, 3, "mix_mat_set", "m");
  cinterpolate_free(internal->interpolate_m);
  internal->interpolate_m = cinterpolate_alloc("constant", internal->dim_tt_matrix, internal->dim_m, internal->tt_matrix, internal->mix_mat_set, true, false);
  return R_NilValue;
}
SEXP SEIR_metadata(SEXP internal_p) {
  SEIR_internal *internal = SEIR_get_internal(internal_p, 1);
  SEXP ret = PROTECT(allocVector(VECSXP, 4));
  SEXP nms = PROTECT(allocVector(STRSXP, 4));
  SET_STRING_ELT(nms, 0, mkChar("variable_order"));
  SET_STRING_ELT(nms, 1, mkChar("output_order"));
  SET_STRING_ELT(nms, 2, mkChar("n_out"));
  SET_STRING_ELT(nms, 3, mkChar("interpolate_t"));
  setAttrib(ret, R_NamesSymbol, nms);
  SEXP variable_length = PROTECT(allocVector(VECSXP, 5));
  SEXP variable_names = PROTECT(allocVector(STRSXP, 5));
  setAttrib(variable_length, R_NamesSymbol, variable_names);
  SET_VECTOR_ELT(variable_length, 0, ScalarInteger(internal->dim_S));
  SET_VECTOR_ELT(variable_length, 1, ScalarInteger(internal->dim_E1));
  SET_VECTOR_ELT(variable_length, 2, ScalarInteger(internal->dim_E2));
  SET_VECTOR_ELT(variable_length, 3, ScalarInteger(internal->dim_I));
  SET_VECTOR_ELT(variable_length, 4, ScalarInteger(internal->dim_R));
  SET_STRING_ELT(variable_names, 0, mkChar("S"));
  SET_STRING_ELT(variable_names, 1, mkChar("E1"));
  SET_STRING_ELT(variable_names, 2, mkChar("E2"));
  SET_STRING_ELT(variable_names, 3, mkChar("I"));
  SET_STRING_ELT(variable_names, 4, mkChar("R"));
  SET_VECTOR_ELT(ret, 0, variable_length);
  UNPROTECT(2);
  SEXP output_length = PROTECT(allocVector(VECSXP, 2));
  SEXP output_names = PROTECT(allocVector(STRSXP, 2));
  setAttrib(output_length, R_NamesSymbol, output_names);
  SET_VECTOR_ELT(output_length, 0, R_NilValue);
  SET_VECTOR_ELT(output_length, 1, ScalarInteger(internal->dim_n_EI));
  SET_STRING_ELT(output_names, 0, mkChar("time"));
  SET_STRING_ELT(output_names, 1, mkChar("n_EI"));
  SET_VECTOR_ELT(ret, 1, output_length);
  UNPROTECT(2);
  SET_VECTOR_ELT(ret, 2, ScalarInteger(1 + internal->dim_n_EI));
  SEXP interpolate_t = PROTECT(allocVector(VECSXP, 3));
  SEXP interpolate_t_nms = PROTECT(allocVector(STRSXP, 3));
  setAttrib(interpolate_t, R_NamesSymbol, interpolate_t_nms);
  SET_VECTOR_ELT(interpolate_t, 0, ScalarReal(fmax(internal->tt_beta[0], internal->tt_matrix[0])));
  SET_VECTOR_ELT(interpolate_t, 1, ScalarReal(R_PosInf));
  SET_STRING_ELT(interpolate_t_nms, 0, mkChar("min"));
  SET_STRING_ELT(interpolate_t_nms, 1, mkChar("max"));
  SET_VECTOR_ELT(ret, 3, interpolate_t);
  UNPROTECT(2);
  UNPROTECT(2);
  return ret;
}
SEXP SEIR_initial_conditions(SEXP internal_p, SEXP step_ptr) {
  SEIR_internal *internal = SEIR_get_internal(internal_p, 1);
  SEXP r_state = PROTECT(allocVector(REALSXP, internal->dim_S + internal->dim_E1 + internal->dim_E2 + internal->dim_I + internal->dim_R));
  double * state = REAL(r_state);
  memcpy(state + 0, internal->initial_S, internal->dim_S * sizeof(double));
  memcpy(state + internal->dim_S, internal->initial_E1, internal->dim_E1 * sizeof(double));
  memcpy(state + internal->offset_variable_E2, internal->initial_E2, internal->dim_E2 * sizeof(double));
  memcpy(state + internal->offset_variable_I, internal->initial_I, internal->dim_I * sizeof(double));
  memcpy(state + internal->offset_variable_R, internal->initial_R, internal->dim_R * sizeof(double));
  UNPROTECT(1);
  return r_state;
}
void SEIR_rhs(SEIR_internal* internal, size_t step, double * state, double * state_next, double * output) {
  double * S = state + 0;
  double * E1 = state + internal->dim_S;
  double * E2 = state + internal->offset_variable_E2;
  double * I = state + internal->offset_variable_I;
  double * R = state + internal->offset_variable_R;
  for (int i = 1; i <= internal->dim_n_EE; ++i) {
    internal->n_EE[i - 1] = Rf_rbinom(round(E1[i - 1]), internal->p_EE);
  }
  for (int i = 1; i <= internal->dim_n_EI; ++i) {
    internal->n_EI[i - 1] = Rf_rbinom(round(E2[i - 1]), internal->p_EI);
  }
  for (int i = 1; i <= internal->dim_n_IR; ++i) {
    internal->n_IR[i - 1] = Rf_rbinom(round(I[i - 1]), internal->p_IR);
  }
  for (int i = 1; i <= internal->dim_temp; ++i) {
    internal->temp[i - 1] = I[i - 1];
  }
  for (int i = 1; i <= internal->dim_delta_E2; ++i) {
    internal->delta_E2[i - 1] = internal->n_EE[i - 1] - internal->n_EI[i - 1];
  }
  for (int i = 1; i <= internal->dim_delta_I; ++i) {
    internal->delta_I[i - 1] = internal->n_EI[i - 1] - internal->n_IR[i - 1];
  }
  for (int i = 1; i <= internal->dim_delta_R; ++i) {
    internal->delta_R[i - 1] = internal->n_IR[i - 1];
  }
  double beta = 0.0;
  cinterpolate_eval(step, internal->interpolate_beta, &beta);
  for (int i = 1; i <= internal->dim_E2; ++i) {
    state_next[internal->offset_variable_E2 + i - 1] = E2[i - 1] + internal->delta_E2[i - 1];
  }
  for (int i = 1; i <= internal->dim_I; ++i) {
    state_next[internal->offset_variable_I + i - 1] = I[i - 1] + internal->delta_I[i - 1];
  }
  for (int i = 1; i <= internal->dim_R; ++i) {
    state_next[internal->offset_variable_R + i - 1] = R[i - 1] + internal->delta_R[i - 1];
  }
  cinterpolate_eval(step, internal->interpolate_m, internal->m);
  for (int i = 1; i <= internal->dim_s_ij_1; ++i) {
    for (int j = 1; j <= internal->dim_s_ij_2; ++j) {
      internal->s_ij[i - 1 + internal->dim_s_ij_1 * (j - 1)] = internal->m[internal->dim_m_1 * (j - 1) + i - 1] * internal->temp[j - 1];
    }
  }
  for (int i = 1; i <= internal->dim_lambda; ++i) {
    internal->lambda[i - 1] = beta * odin_sum2(internal->s_ij, i - 1, i, 0, internal->dim_s_ij_2, internal->dim_s_ij_1);
  }
  for (int i = 1; i <= internal->dim_p_SE; ++i) {
    internal->p_SE[i - 1] = 1 - exp(-(internal->lambda[i - 1]) * internal->dt);
  }
  for (int i = 1; i <= internal->dim_n_SE; ++i) {
    internal->n_SE[i - 1] = Rf_rbinom(round(S[i - 1]), internal->p_SE[i - 1]);
  }
  for (int i = 1; i <= internal->dim_delta_E1; ++i) {
    internal->delta_E1[i - 1] = internal->n_SE[i - 1] - internal->n_EE[i - 1];
  }
  for (int i = 1; i <= internal->dim_S; ++i) {
    state_next[0 + i - 1] = S[i - 1] - internal->n_SE[i - 1];
  }
  for (int i = 1; i <= internal->dim_E1; ++i) {
    state_next[internal->dim_S + i - 1] = E1[i - 1] + internal->delta_E1[i - 1];
  }
  double time = step * internal->dt;
  output[0] = time;
  memcpy(output + 1, internal->n_EI, internal->dim_n_EI * sizeof(double));
}
void SEIR_rhs_dde(size_t n_eq, size_t step, double * state, double * state_next, size_t n_out, double * output, void * internal) {
  SEIR_rhs((SEIR_internal*)internal, step, state, state_next, output);
}
SEXP SEIR_rhs_r(SEXP internal_p, SEXP step, SEXP state) {
  SEXP state_next = PROTECT(allocVector(REALSXP, LENGTH(state)));
  SEIR_internal *internal = SEIR_get_internal(internal_p, 1);
  SEXP output_ptr = PROTECT(allocVector(REALSXP, 1 + internal->dim_n_EI));
  setAttrib(state_next, install("output"), output_ptr);
  UNPROTECT(1);
  double *output = REAL(output_ptr);
  GetRNGstate();
  SEIR_rhs(internal, INTEGER(step)[0], REAL(state), REAL(state_next), output);
  PutRNGstate();
  UNPROTECT(1);
  return state_next;
}
double user_get_scalar_double(SEXP user, const char *name,
                              double default_value, double min, double max) {
  double ret = default_value;
  SEXP el = user_list_element(user, name);
  if (el != R_NilValue) {
    if (length(el) != 1) {
      Rf_error("Expected a scalar numeric for '%s'", name);
    }
    if (TYPEOF(el) == REALSXP) {
      ret = REAL(el)[0];
    } else if (TYPEOF(el) == INTSXP) {
      ret = INTEGER(el)[0];
    } else {
      Rf_error("Expected a numeric value for %s", name);
    }
  }
  if (ISNA(ret)) {
    Rf_error("Expected a value for '%s'", name);
  }
  user_check_values_double(&ret, 1, min, max, name);
  return ret;
}
int user_get_scalar_int(SEXP user, const char *name,
                        int default_value, double min, double max) {
  int ret = default_value;
  SEXP el = user_list_element(user, name);
  if (el != R_NilValue) {
    if (length(el) != 1) {
      Rf_error("Expected scalar integer for %d", name);
    }
    if (TYPEOF(el) == REALSXP) {
      double tmp = REAL(el)[0];
      if (fabs(tmp - round(tmp)) > 2e-8) {
        Rf_error("Expected '%s' to be integer-like", name);
      }
    }
    ret = INTEGER(coerceVector(el, INTSXP))[0];
  }
  if (ret == NA_INTEGER) {
    Rf_error("Expected a value for '%s'", name);
  }
  user_check_values_int(&ret, 1, min, max, name);
  return ret;
}
void user_check_values_double(double * value, size_t len,
                                  double min, double max, const char *name) {
  for (size_t i = 0; i < len; ++i) {
    if (ISNA(value[i])) {
      Rf_error("'%s' must not contain any NA values", name);
    }
  }
  if (min != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] < min) {
        Rf_error("Expected '%s' to be at least %g", name, min);
      }
    }
  }
  if (max != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] > max) {
        Rf_error("Expected '%s' to be at most %g", name, max);
      }
    }
  }
}
void user_check_values_int(int * value, size_t len,
                               double min, double max, const char *name) {
  for (size_t i = 0; i < len; ++i) {
    if (ISNA(value[i])) {
      Rf_error("'%s' must not contain any NA values", name);
    }
  }
  if (min != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] < min) {
        Rf_error("Expected '%s' to be at least %g", name, min);
      }
    }
  }
  if (max != NA_REAL) {
    for (size_t i = 0; i < len; ++i) {
      if (value[i] > max) {
        Rf_error("Expected '%s' to be at most %g", name, max);
      }
    }
  }
}
void user_check_values(SEXP value, double min, double max,
                           const char *name) {
  size_t len = (size_t)length(value);
  if (TYPEOF(value) == INTSXP) {
    user_check_values_int(INTEGER(value), len, min, max, name);
  } else {
    user_check_values_double(REAL(value), len, min, max, name);
  }
}
SEXP user_list_element(SEXP list, const char *name) {
  SEXP ret = R_NilValue, names = getAttrib(list, R_NamesSymbol);
  for (int i = 0; i < length(list); ++i) {
    if(strcmp(CHAR(STRING_ELT(names, i)), name) == 0) {
      ret = VECTOR_ELT(list, i);
      break;
    }
  }
  return ret;
}
void odin_set_dim(SEXP target, int rank, ...) {
  SEXP r_dim = PROTECT(allocVector(INTSXP, rank));
  int *dim = INTEGER(r_dim);

  va_list ap;
  va_start(ap, rank);
  for (size_t i = 0; i < (size_t)rank; ++i) {
    dim[i] = va_arg(ap, int);
  }
  va_end(ap);

  setAttrib(target, R_DimSymbol, r_dim);
  UNPROTECT(1);
}
void* user_get_array_dim(SEXP user, bool is_integer, void * previous,
                         const char *name, int rank,
                         double min, double max, int *dest_dim) {
  SEXP el = user_get_array_check_rank(user, name, rank, previous == NULL);
  if (el == R_NilValue) {
    return previous;
  }

  dest_dim[0] = LENGTH(el);
  if (rank > 1) {
    SEXP r_dim = PROTECT(coerceVector(getAttrib(el, R_DimSymbol), INTSXP));
    int *dim = INTEGER(r_dim);

    for (size_t i = 0; i < (size_t) rank; ++i) {
      dest_dim[i + 1] = dim[i];
    }

    UNPROTECT(1);
  }

  el = PROTECT(user_get_array_check(el, is_integer, name, min, max));

  int len = LENGTH(el);
  void *dest = NULL;
  if (is_integer) {
    dest = Calloc(len, int);
    memcpy(dest, INTEGER(el), len * sizeof(int));
  } else {
    dest = Calloc(len, double);
    memcpy(dest, REAL(el), len * sizeof(double));
  }
  Free(previous);

  UNPROTECT(1);

  return dest;
}
void* user_get_array(SEXP user, bool is_integer, void * previous,
                     const char *name, double min, double max,
                     int rank, ...) {
  SEXP el = user_get_array_check_rank(user, name, rank, previous == NULL);
  if (el == R_NilValue) {
    return previous;
  }

  SEXP r_dim;
  int *dim;

  size_t len = LENGTH(el);
  if (rank == 1) {
    r_dim = PROTECT(ScalarInteger(len));
  } else {
    r_dim = PROTECT(coerceVector(getAttrib(el, R_DimSymbol), INTSXP));
  }
  dim = INTEGER(r_dim);

  va_list ap;
  va_start(ap, rank);
  for (size_t i = 0; i < (size_t) rank; ++i) {
    int dim_expected = va_arg(ap, int);
    if (dim[i] != dim_expected) {
      va_end(ap); // avoid a leak
      if (rank == 1) {
        Rf_error("Expected length %d value for %s", dim_expected, name);
      } else {
        Rf_error("Incorrect size of dimension %d of %s (expected %d)",
                 i + 1, name, dim_expected);
      }
    }
  }
  va_end(ap);
  UNPROTECT(1);

  el = PROTECT(user_get_array_check(el, is_integer, name, min, max));

  void *dest = NULL;
  if (is_integer) {
    dest = Calloc(len, int);
    memcpy(dest, INTEGER(el), len * sizeof(int));
  } else {
    dest = Calloc(len, double);
    memcpy(dest, REAL(el), len * sizeof(double));
  }
  Free(previous);

  UNPROTECT(1);

  return dest;
}
SEXP user_get_array_check(SEXP el, bool is_integer, const char *name,
                          double min, double max) {
  size_t len = (size_t) length(el);
  if (is_integer) {
    if (TYPEOF(el) == INTSXP) {
      user_check_values_int(INTEGER(el), len, min, max, name);
    } else if (TYPEOF(el) == REALSXP) {
      el = PROTECT(coerceVector(el, INTSXP));
      user_check_values_int(INTEGER(el), len, min, max, name);
      UNPROTECT(1);
    } else {
      Rf_error("Expected a integer value for %s", name);
    }
  } else {
    if (TYPEOF(el) == INTSXP) {
      el = PROTECT(coerceVector(el, REALSXP));
      user_check_values_double(REAL(el), len, min, max, name);
      UNPROTECT(1);
    } else if (TYPEOF(el) == REALSXP) {
      user_check_values_double(REAL(el), len, min, max, name);
    } else {
      Rf_error("Expected a numeric value for %s", name);
    }
  }
  return el;
}
SEXP user_get_array_check_rank(SEXP user, const char *name, int rank,
                               bool required) {
  SEXP el = user_list_element(user, name);
  if (el == R_NilValue) {
    if (required) {
      Rf_error("Expected a value for '%s'", name);
    }
  } else {
    if (rank == 1) {
      if (isArray(el)) {
        Rf_error("Expected a numeric vector for '%s'", name);
      }
    } else {
      SEXP r_dim = getAttrib(el, R_DimSymbol);
      if (r_dim == R_NilValue || LENGTH(r_dim) != rank) {
        if (rank == 2) {
          Rf_error("Expected a numeric matrix for '%s'", name);
        } else {
          Rf_error("Expected a numeric array of rank %d for '%s'", rank, name);
        }
      }
    }
  }
  return el;
}
void interpolate_check_y(size_t nx, size_t ny, size_t i, const char *name_arg, const char *name_target) {
  if (nx != ny) {
    if (i == 0) {
      // vector case
      Rf_error("Expected %s to have length %d (for %s)",
               name_arg, nx, name_target);
    } else {
      // array case
      Rf_error("Expected dimension %d of %s to have size %d (for %s)",
               i, name_arg, nx, name_target);
    }
  }
}
double odin_sum1(double *x, size_t from, size_t to) {
  double tot = 0.0;
  for (size_t i = from; i < to; ++i) {
    tot += x[i];
  }
  return tot;
}
double odin_sum2(double* x, int from_i, int to_i, int from_j, int to_j, int dim_x_1) {
  double tot = 0.0;
  for (int j = from_j; j < to_j; ++j) {
    int jj = j * dim_x_1;
    for (int i = from_i; i < to_i; ++i) {
      tot += x[i + jj];
    }
  }
  return tot;
}
double odin_sum3(double* x, int from_i, int to_i, int from_j, int to_j, int from_k, int to_k, int dim_x_1, int dim_x_12) {
  double tot = 0.0;
  for (int k = from_k; k < to_k; ++k) {
    int kk = k * dim_x_12;
    for (int j = from_j; j < to_j; ++j) {
      int jj = j * dim_x_1 + kk;
      for (int i = from_i; i < to_i; ++i) {
        tot += x[i + jj];
      }
    }
  }
  return tot;
}
// This construction is to help odin
#ifndef CINTERPOLTE_CINTERPOLATE_H_
#endif


void * cinterpolate_alloc(const char *type, size_t n, size_t ny,
                          double *x, double *y, bool fail_on_extrapolate,
                          bool auto_clean) {
  typedef void* interpolate_alloc_t(const char *, size_t, size_t,
                                    double*, double*, bool, bool);
  static interpolate_alloc_t *fun;
  if (fun == NULL) {
    fun = (interpolate_alloc_t*)
      R_GetCCallable("cinterpolate", "interpolate_alloc");
  }
  return fun(type, n, ny, x, y, fail_on_extrapolate, auto_clean);
}


int cinterpolate_eval(double x, void *obj, double *y) {
  typedef int interpolate_eval_t(double, void*, double*);
  static interpolate_eval_t *fun;
  if (fun == NULL) {
    fun = (interpolate_eval_t*)
      R_GetCCallable("cinterpolate", "interpolate_eval");
  }
  return fun(x, obj, y);
}


void cinterpolate_free(void *obj) {
  typedef int interpolate_free_t(void*);
  static interpolate_free_t *fun;
  if (fun == NULL) {
    fun = (interpolate_free_t*)
      R_GetCCallable("cinterpolate", "interpolate_free");
  }
  fun(obj);
}
