## Automatically generated by odin - do not edit
.explicit_SEIR <- odin:::odin_c_class("explicit_SEIR", list(get_internal = "explicit_SEIR_get_internal", finalise = "explicit_SEIR_finalise", create = "explicit_SEIR_create", initmod_desolve = "explicit_SEIR_initmod_desolve", contents = "explicit_SEIR_contents", set_user = "explicit_SEIR_set_user", metadata = "explicit_SEIR_metadata", initial_conditions = "explicit_SEIR_initial_conditions", rhs = "explicit_SEIR_rhs", rhs_dde = "explicit_SEIR_rhs_dde", rhs_r = "explicit_SEIR_rhs_r"), c("beta_set", "D_0", "dt", "E1_0", "E2_0", "gamma_E", "gamma_get_mv_die", "gamma_get_mv_survive", "gamma_get_ox_die", "gamma_get_ox_survive", "gamma_ICase", "gamma_IMild", "gamma_not_get_mv_die", "gamma_not_get_mv_survive", "gamma_not_get_ox_die", "gamma_not_get_ox_survive", "gamma_rec", "hosp_beds", "ICase1_0", "ICase2_0", "ICU_beds", "IMild_0", "IMVGetDie1_0", "IMVGetDie2_0", "IMVGetLive1_0", "IMVGetLive2_0", "IMVNotGetDie1_0", "IMVNotGetDie2_0", "IMVNotGetLive1_0", "IMVNotGetLive2_0", "IOxGetDie1_0", "IOxGetDie2_0", "IOxGetLive1_0", "IOxGetLive2_0", "IOxNotGetDie1_0", "IOxNotGetDie2_0", "IOxNotGetLive1_0", "IOxNotGetLive2_0", "IRec1_0", "IRec2_0", "mix_mat_set", "N_age", "p_dist", "prob_hosp", "prob_non_severe_death_no_treatment", "prob_non_severe_death_treatment", "prob_severe", "prob_severe_death_no_treatment", "prob_severe_death_treatment", "R_0", "S_0", "tt_beta", "tt_hosp_beds", "tt_ICU_beds", "tt_matrix"), list(discrete = TRUE, has_array = TRUE, has_output = TRUE, has_user = TRUE, has_delay = FALSE, has_interpolate = TRUE, has_stochastic = TRUE, has_include = FALSE, initial_time_dependent = FALSE, safe = FALSE), "squire", "odin/explicit_SEIR.json", TRUE)
explicit_SEIR <- structure(function (beta_set, D_0, dt, E1_0, E2_0, gamma_E, gamma_get_mv_die,
    gamma_get_mv_survive, gamma_get_ox_die, gamma_get_ox_survive,
    gamma_ICase, gamma_IMild, gamma_not_get_mv_die, gamma_not_get_mv_survive,
    gamma_not_get_ox_die, gamma_not_get_ox_survive, gamma_rec,
    hosp_beds, ICase1_0, ICase2_0, ICU_beds, IMild_0, IMVGetDie1_0,
    IMVGetDie2_0, IMVGetLive1_0, IMVGetLive2_0, IMVNotGetDie1_0,
    IMVNotGetDie2_0, IMVNotGetLive1_0, IMVNotGetLive2_0, IOxGetDie1_0,
    IOxGetDie2_0, IOxGetLive1_0, IOxGetLive2_0, IOxNotGetDie1_0,
    IOxNotGetDie2_0, IOxNotGetLive1_0, IOxNotGetLive2_0, IRec1_0,
    IRec2_0, mix_mat_set, N_age, p_dist, prob_hosp, prob_non_severe_death_no_treatment,
    prob_non_severe_death_treatment, prob_severe, prob_severe_death_no_treatment,
    prob_severe_death_treatment, R_0, S_0, tt_beta, tt_hosp_beds,
    tt_ICU_beds, tt_matrix, user = list(beta_set = beta_set,
        D_0 = D_0, dt = dt, E1_0 = E1_0, E2_0 = E2_0, gamma_E = gamma_E,
        gamma_get_mv_die = gamma_get_mv_die, gamma_get_mv_survive = gamma_get_mv_survive,
        gamma_get_ox_die = gamma_get_ox_die, gamma_get_ox_survive = gamma_get_ox_survive,
        gamma_ICase = gamma_ICase, gamma_IMild = gamma_IMild,
        gamma_not_get_mv_die = gamma_not_get_mv_die, gamma_not_get_mv_survive = gamma_not_get_mv_survive,
        gamma_not_get_ox_die = gamma_not_get_ox_die, gamma_not_get_ox_survive = gamma_not_get_ox_survive,
        gamma_rec = gamma_rec, hosp_beds = hosp_beds, ICase1_0 = ICase1_0,
        ICase2_0 = ICase2_0, ICU_beds = ICU_beds, IMild_0 = IMild_0,
        IMVGetDie1_0 = IMVGetDie1_0, IMVGetDie2_0 = IMVGetDie2_0,
        IMVGetLive1_0 = IMVGetLive1_0, IMVGetLive2_0 = IMVGetLive2_0,
        IMVNotGetDie1_0 = IMVNotGetDie1_0, IMVNotGetDie2_0 = IMVNotGetDie2_0,
        IMVNotGetLive1_0 = IMVNotGetLive1_0, IMVNotGetLive2_0 = IMVNotGetLive2_0,
        IOxGetDie1_0 = IOxGetDie1_0, IOxGetDie2_0 = IOxGetDie2_0,
        IOxGetLive1_0 = IOxGetLive1_0, IOxGetLive2_0 = IOxGetLive2_0,
        IOxNotGetDie1_0 = IOxNotGetDie1_0, IOxNotGetDie2_0 = IOxNotGetDie2_0,
        IOxNotGetLive1_0 = IOxNotGetLive1_0, IOxNotGetLive2_0 = IOxNotGetLive2_0,
        IRec1_0 = IRec1_0, IRec2_0 = IRec2_0, mix_mat_set = mix_mat_set,
        N_age = N_age, p_dist = p_dist, prob_hosp = prob_hosp,
        prob_non_severe_death_no_treatment = prob_non_severe_death_no_treatment,
        prob_non_severe_death_treatment = prob_non_severe_death_treatment,
        prob_severe = prob_severe, prob_severe_death_no_treatment = prob_severe_death_no_treatment,
        prob_severe_death_treatment = prob_severe_death_treatment,
        R_0 = R_0, S_0 = S_0, tt_beta = tt_beta, tt_hosp_beds = tt_hosp_beds,
        tt_ICU_beds = tt_ICU_beds, tt_matrix = tt_matrix), unused_user_action = NULL)
{
    .explicit_SEIR$new(user, unused_user_action)
}, ir = "odin/explicit_SEIR.json", class = "odin_generator")
class(explicit_SEIR) <- "odin_generator"
attr(explicit_SEIR, "ir") <- .explicit_SEIR$public_fields$ir
.explict_SEIR_fix <- odin:::odin_c_class("explict_SEIR_fix", list(get_internal = "explict_SEIR_fix_get_internal", finalise = "explict_SEIR_fix_finalise", create = "explict_SEIR_fix_create", initmod_desolve = "explict_SEIR_fix_initmod_desolve", contents = "explict_SEIR_fix_contents", set_user = "explict_SEIR_fix_set_user", metadata = "explict_SEIR_fix_metadata", initial_conditions = "explict_SEIR_fix_initial_conditions", rhs = "explict_SEIR_fix_rhs", rhs_dde = "explict_SEIR_fix_rhs_dde", rhs_r = "explict_SEIR_fix_rhs_r"), c("beta_set", "D_0", "dt", "E1_0", "E2_0", "gamma_E", "gamma_get_mv_die", "gamma_get_mv_survive", "gamma_get_ox_die", "gamma_get_ox_survive", "gamma_ICase", "gamma_IMild", "gamma_not_get_mv_die", "gamma_not_get_mv_survive", "gamma_not_get_ox_die", "gamma_not_get_ox_survive", "gamma_rec", "hosp_beds", "ICase1_0", "ICase2_0", "ICU_beds", "IMild_0", "IMVGetDie1_0", "IMVGetDie2_0", "IMVGetLive1_0", "IMVGetLive2_0", "IMVNotGetDie1_0", "IMVNotGetDie2_0", "IMVNotGetLive1_0", "IMVNotGetLive2_0", "IOxGetDie1_0", "IOxGetDie2_0", "IOxGetLive1_0", "IOxGetLive2_0", "IOxNotGetDie1_0", "IOxNotGetDie2_0", "IOxNotGetLive1_0", "IOxNotGetLive2_0", "IRec1_0", "IRec2_0", "mix_mat_set", "N_age", "p_dist", "prob_hosp", "prob_non_severe_death_no_treatment", "prob_non_severe_death_treatment", "prob_severe", "prob_severe_death_no_treatment", "prob_severe_death_treatment", "R_0", "S_0", "tt_beta", "tt_hosp_beds", "tt_ICU_beds", "tt_matrix"), list(discrete = TRUE, has_array = TRUE, has_output = TRUE, has_user = TRUE, has_delay = FALSE, has_interpolate = TRUE, has_stochastic = TRUE, has_include = FALSE, initial_time_dependent = FALSE, safe = FALSE), "squire", "odin/explict_SEIR_fix.json", TRUE)
explict_SEIR_fix <- structure(function (beta_set, D_0, dt, E1_0, E2_0, gamma_E, gamma_get_mv_die,
    gamma_get_mv_survive, gamma_get_ox_die, gamma_get_ox_survive,
    gamma_ICase, gamma_IMild, gamma_not_get_mv_die, gamma_not_get_mv_survive,
    gamma_not_get_ox_die, gamma_not_get_ox_survive, gamma_rec,
    hosp_beds, ICase1_0, ICase2_0, ICU_beds, IMild_0, IMVGetDie1_0,
    IMVGetDie2_0, IMVGetLive1_0, IMVGetLive2_0, IMVNotGetDie1_0,
    IMVNotGetDie2_0, IMVNotGetLive1_0, IMVNotGetLive2_0, IOxGetDie1_0,
    IOxGetDie2_0, IOxGetLive1_0, IOxGetLive2_0, IOxNotGetDie1_0,
    IOxNotGetDie2_0, IOxNotGetLive1_0, IOxNotGetLive2_0, IRec1_0,
    IRec2_0, mix_mat_set, N_age, p_dist, prob_hosp, prob_non_severe_death_no_treatment,
    prob_non_severe_death_treatment, prob_severe, prob_severe_death_no_treatment,
    prob_severe_death_treatment, R_0, S_0, tt_beta, tt_hosp_beds,
    tt_ICU_beds, tt_matrix, user = list(beta_set = beta_set,
        D_0 = D_0, dt = dt, E1_0 = E1_0, E2_0 = E2_0, gamma_E = gamma_E,
        gamma_get_mv_die = gamma_get_mv_die, gamma_get_mv_survive = gamma_get_mv_survive,
        gamma_get_ox_die = gamma_get_ox_die, gamma_get_ox_survive = gamma_get_ox_survive,
        gamma_ICase = gamma_ICase, gamma_IMild = gamma_IMild,
        gamma_not_get_mv_die = gamma_not_get_mv_die, gamma_not_get_mv_survive = gamma_not_get_mv_survive,
        gamma_not_get_ox_die = gamma_not_get_ox_die, gamma_not_get_ox_survive = gamma_not_get_ox_survive,
        gamma_rec = gamma_rec, hosp_beds = hosp_beds, ICase1_0 = ICase1_0,
        ICase2_0 = ICase2_0, ICU_beds = ICU_beds, IMild_0 = IMild_0,
        IMVGetDie1_0 = IMVGetDie1_0, IMVGetDie2_0 = IMVGetDie2_0,
        IMVGetLive1_0 = IMVGetLive1_0, IMVGetLive2_0 = IMVGetLive2_0,
        IMVNotGetDie1_0 = IMVNotGetDie1_0, IMVNotGetDie2_0 = IMVNotGetDie2_0,
        IMVNotGetLive1_0 = IMVNotGetLive1_0, IMVNotGetLive2_0 = IMVNotGetLive2_0,
        IOxGetDie1_0 = IOxGetDie1_0, IOxGetDie2_0 = IOxGetDie2_0,
        IOxGetLive1_0 = IOxGetLive1_0, IOxGetLive2_0 = IOxGetLive2_0,
        IOxNotGetDie1_0 = IOxNotGetDie1_0, IOxNotGetDie2_0 = IOxNotGetDie2_0,
        IOxNotGetLive1_0 = IOxNotGetLive1_0, IOxNotGetLive2_0 = IOxNotGetLive2_0,
        IRec1_0 = IRec1_0, IRec2_0 = IRec2_0, mix_mat_set = mix_mat_set,
        N_age = N_age, p_dist = p_dist, prob_hosp = prob_hosp,
        prob_non_severe_death_no_treatment = prob_non_severe_death_no_treatment,
        prob_non_severe_death_treatment = prob_non_severe_death_treatment,
        prob_severe = prob_severe, prob_severe_death_no_treatment = prob_severe_death_no_treatment,
        prob_severe_death_treatment = prob_severe_death_treatment,
        R_0 = R_0, S_0 = S_0, tt_beta = tt_beta, tt_hosp_beds = tt_hosp_beds,
        tt_ICU_beds = tt_ICU_beds, tt_matrix = tt_matrix), unused_user_action = NULL)
{
    .explict_SEIR_fix$new(user, unused_user_action)
}, ir = "odin/explict_SEIR_fix.json", class = "odin_generator")
class(explict_SEIR_fix) <- "odin_generator"
attr(explict_SEIR_fix, "ir") <- .explict_SEIR_fix$public_fields$ir
.simple_SEIR <- odin:::odin_c_class("simple_SEIR", list(get_internal = "simple_SEIR_get_internal", finalise = "simple_SEIR_finalise", create = "simple_SEIR_create", initmod_desolve = "simple_SEIR_initmod_desolve", contents = "simple_SEIR_contents", set_user = "simple_SEIR_set_user", metadata = "simple_SEIR_metadata", initial_conditions = "simple_SEIR_initial_conditions", rhs = "simple_SEIR_rhs", rhs_dde = "simple_SEIR_rhs_dde", rhs_r = "simple_SEIR_rhs_r"), c("beta_set", "dt", "E0", "E02", "gamma_E", "gamma_I", "I0", "mix_mat_set", "N_age", "R0", "S0", "tt_beta", "tt_matrix"), list(discrete = TRUE, has_array = TRUE, has_output = TRUE, has_user = TRUE, has_delay = FALSE, has_interpolate = TRUE, has_stochastic = TRUE, has_include = FALSE, initial_time_dependent = FALSE, safe = FALSE), "squire", "odin/simple_SEIR.json", TRUE)
simple_SEIR <- structure(function (beta_set, dt, E0, E02, gamma_E, gamma_I,
    I0, mix_mat_set, N_age, R0, S0, tt_beta, tt_matrix, user = list(beta_set = beta_set,
        dt = dt, E0 = E0, E02 = E02, gamma_E = gamma_E, gamma_I = gamma_I,
        I0 = I0, mix_mat_set = mix_mat_set, N_age = N_age, R0 = R0,
        S0 = S0, tt_beta = tt_beta, tt_matrix = tt_matrix), unused_user_action = NULL)
{
    .simple_SEIR$new(user, unused_user_action)
}, ir = "odin/simple_SEIR.json", class = "odin_generator")
class(simple_SEIR) <- "odin_generator"
attr(simple_SEIR, "ir") <- .simple_SEIR$public_fields$ir
